@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImVtYWlsIjoianVsaWFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDkxMDQ4NDcsImV4cCI6MTc0OTEwODQ0N30.DHJHmFhYq71Hg83fjkHxGqoL6PmaTp_6PwNjHzTeh2k
GET http://localhost:8000/events
    ?limit=2
    &page=1

### Get Event Details
GET http://localhost:8000/events/1
Authorization : Bearer {{access_token}}

###
POST http://localhost:8000/events
Authorization : Bearer {{access_token}}
Content-Type: application/json

{
  "event_name": "Tech Conference 2025",
  "event_date": "2025-06-15",
  "event_location": "Nairobi Convention Center",
  "event_description": "Annual tech conference featuring the latest innovations in tech",
  "userId": 3
}



###
PATCH http://localhost:8000/events/1
Authorization : Bearer {{access_token}}
Content-Type: application/json

{
  "event_name": "Decode Tech Conference 2025",
  "id": 1,
  "event_location": "New Nairobi Convention Center",
  "event_description": "Decode description with more details about the conference"
}