###
GET http://localhost:8000/eventsRegistration

###
POST http://localhost:8000/eventsRegistration
Content-Type: application/json

{
  "eventId":1,
  "userId": 1,
  "paymentStatus":"PENDING",
  "amount":300
}