services:
  redis:
    image: redis:7-alpine
    container_name: redis_container
    ports:
      - '6379:6379'
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    networks:
      - redis_network
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
networks:
  redis_network:
    driver: bridge
