###
GET http://localhost:8000/users



###
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@gmail.com",
    "password": "Password123!",
    "phone": "123-456-7890",
    "role": "organiser"
}