###
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI2LCJlbWFpbCI6Im13YW5naWtlbjEyOUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDk1ODczMjAsImV4cCI6MTc0OTU5MDkyMH0.JsLTzH6-xNeXW5wLVsFTsiADW741Qqpvum19HnvKv0o
GET http://localhost:8000/users/1
Authorization: Bearer {{access_token}}
###
GET http://localhost:8000/users
?limit=1
&page=1
Authorization: Bearer {{@access_token}}


GET http://localhost:8000/users?limit=2&page=1
Authorization: Bearer {{access_token}}



###
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "ashley doe",
    "email": "ashley5@gmail.com",
    "password": "Password123!",
    "phone": "123-456-7890",
    "role": "organizer"
}



### Update User
PATCH http://localhost:8000/users/1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  
  "name": "John Updated",
  "password": "Password123!"
}


### John login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "john@gmail.com",
  "password": "Password123!"
}