@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImVtYWlsIjoianVsaWFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDk0NjkwMDksImV4cCI6MTc0OTQ3MjYwOX0.Qjr6oJmIvJeZmXC0WCm7ceD4hOXaYKP6Th4sMFPm5dY,
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImVtYWlsIjoianVsaWFAZ21haWwuY29tIiwiaWF0IjoxNzQ5NDY5MDA5LCJleHAiOjE3NDk0Njk2MTN9.EX15Sn_UAFJv0l0d62HcVTw_oAUlwrz6sxUkMVKtP3k,
@url = http://localhost:8000

@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMyLCJlbWFpbCI6Imp1bGlhMkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc0OTc1NTA4NywiZXhwIjoxNzQ5NzU4Njg3fQ._UV_iptgwA4bB2oPifREYipWGRpu8RD0LTz-WsKeNi4

@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiamFtZXNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ5NzU1MTgzLCJleHAiOjE3NDk3NTg3ODN9.4797e08_E9TgYShkOC4nLPwmozvUvOHnCU1GbYkgqyQ


### User Registration
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "julia Doe",
    "email": "julia2@gmail.com",
    "password": "Password123!",
    "phone": "123-456-7890",
    "role": "user"
}

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "mwangi ken",
    "email": "mwangiken128@gmail.com",
    "password": "Password1234!",
    "phone": "123-456-7890",
    "role": "user"
}



### User Login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "julia2@gmail.com",
    "password": "Password123!"
}


### admin

POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "james@gmail.com",
    "password": "Password123!"
}
###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "mwangiken128@gmail.com",
    "password": "Password1234!"
}
###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "jane@gmail.com",
    "password": "Password1234!"
}

###
GET {{url}}/auth/refresh
Authorization: Bearer {{refreshToken}}



GET {{url}}/auth/signout/1
Authorization: Bearer {{refreshToken}}


### Get User Profile
GET {{url}}/auth/refresh
Authorization: Bearer {{refreshToken}}

####
GET {{url}}/auth/refresh

//requestReset
#### Request Password Reset
POST {{url}}/auth/password-reset-request
Content-Type: application/json

{
  "email": "mwangiken128@gmail.com"
}

####
POST {{url}}/auth/password-reset
Content-Type: application/json

{
  "email": "mwangiken128@gmail.com",
  "otp": "612572",
  "secret": "MV6WGXTMNZSDU3CYHM6DYWZFG54G6VB6",
  "password": "Password1234!"
}




